services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    ports:
      - "3000:3000"
    environment:
      LOG_LEVEL: info
      LOG_FORMAT: json
    volumes:
      - ./waha-sessions:/waha/sessions
      - ./waha-screenshots:/waha/screenshots
