services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    ports:
      - "192.168.1.108:3000:3000"
    env_file:
      - .env
    environment:
      LOG_LEVEL: info
      LOG_FORMAT: json
    volumes:
      - ./waha-sessions:/waha/sessions
      - ./waha-screenshots:/waha/screenshots
