name: Deploy to Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/noviciado-control-panel
            git pull origin master
            
            echo "Deploying WAHA service..."
            cd waha-service
            docker compose up -d --build
            
            echo "Deploying attendance tracker service..."
            cd ../attendance-tracker
            docker compose up -d --build
